// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7SWntHfKxHB0Q-qrl62L-5J6UPeA6z54',
    appId: '1:1024558465879:web:586e4f3e9b42acbb8df412',
    messagingSenderId: '1024558465879',
    projectId: 'abishek-car-rental-app',
    authDomain: 'abishek-car-rental-app.firebaseapp.com',
    storageBucket: 'abishek-car-rental-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa_UiDKbWiwXa42bwwZpC09iY6jWp2vSQ',
    appId: '1:1024558465879:android:642bf91e2afac2ea8df412',
    messagingSenderId: '1024558465879',
    projectId: 'abishek-car-rental-app',
    storageBucket: 'abishek-car-rental-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfDt_8sp_NJ2YznIg0bdAapS7bXKPwZY',
    appId: '1:1024558465879:ios:c6333c08d9ed530d8df412',
    messagingSenderId: '1024558465879',
    projectId: 'abishek-car-rental-app',
    storageBucket: 'abishek-car-rental-app.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfDt_8sp_NJ2YznIg0bdAapS7bXKPwZY',
    appId: '1:1024558465879:ios:c6333c08d9ed530d8df412',
    messagingSenderId: '1024558465879',
    projectId: 'abishek-car-rental-app',
    storageBucket: 'abishek-car-rental-app.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7SWntHfKxHB0Q-qrl62L-5J6UPeA6z54',
    appId: '1:1024558465879:web:e31e399b4d3e43b58df412',
    messagingSenderId: '1024558465879',
    projectId: 'abishek-car-rental-app',
    authDomain: 'abishek-car-rental-app.firebaseapp.com',
    storageBucket: 'abishek-car-rental-app.firebasestorage.app',
  );
}
